trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'newpipeline-iac'
  location: 'eastus2'
  resourceGroupName: 's1grupoderecursos2'
  virtualNetworkName: 'PRUEBAS1'
  subnetName: 'Subnet-DevOps'
  addressPrefix: '10.0.0.0/16'
  subnetPrefix: '10.0.1.0/24'
  securityGroupName: 'NSG-DevOps'
  publicIpName: 'PublicIP-DevOps'
  vmName: 'VM-DevOps'
  vmSize: 'Standard_B1s' # SKU disponible en eastus2
  adminUsername: 'azureuser'
  adminPassword: 'Password1234' # Contraseña en texto plano (ajustar según necesidad)

  # Variables de la imagen
  imagePublisher: 'Canonical'
  imageOffer: '0001-com-ubuntu-server-jammy'
  imageSku: '22_04-lts-gen2'
  imageVersion: 'latest' # Versión específica de la imagen

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      set -e # Termina el script si cualquier comando falla

      echo "Creando grupo de recursos..."
      az group create --name ${resourceGroupName} --location "${location}"
      echo "Grupo de recursos creado."
